name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Go
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Vet Go code
        run: go vet ./...

      - name: Run Go tests
        #run: go test -mod=readonly -v -race ./...
        run: USER=${{ secrets.API_USERNAME }} PASS=${{ secrets.API_PASSWORD }} go test -v

      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD

      - name: Format code
        run: gofmt -w client.go && gofmt -w client_test.go && gofmt -w http.go && gofmt -w resource.go
